# http://aka.ms/yaml
---
trigger:
- main

pool:
  vmImage: 'windows-latest'

steps:
- script: 'buildAndRun.cmd'
  displayName: Build and run CDS sample exe
  env:
    PA_BT_ORG_SECRET: $(PA_BT_ORG_SECRET)
