trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  name: Restore
  inputs:
    command: 'restore'
    projects: 'OrgServiceSample.csproj'
    configuration: '$(buildConfiguration)'

- task: DotNetCoreCLI@2
  name: Build
  inputs:
    command: 'build'
    projects: 'OrgServiceSample.csproj'
    arguments: '--configuration $(buildConfiguration)'
